# Generated by Django 4.1 on 2022-08-23 16:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelEstudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("clave", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ModelPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("edad", models.IntegerField()),
                ("telefono", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ModelServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=200)),
                ("costo", models.DecimalField(decimal_places=2, max_digits=6)),
                ("Resultado", models.TextField(null=True)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "estudio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.modelestudio",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicios.modelpaciente",
                    ),
                ),
            ],
        ),
    ]
