# Generated by Django 4.1 on 2022-09-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0002_modelestudio_descripcion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modelservicio", old_name="Resultado", new_name="resultado",
        ),
    ]
