# Generated by Django 4.1 on 2022-10-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0004_remove_modelservicio_estudio_modelservicio_estudio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarjetas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "imagen",
                    models.ImageField(default="default.jpg", upload_to="tarjeta"),
                ),
                ("descripcion", models.TextField(null=True)),
            ],
        ),
    ]
