# Generated by Django 4.1 on 2022-10-12 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0007_alter_modelservicio_resultado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelservicio",
            name="paciente",
            field=models.ForeignKey(
                blank=True,
                default=[],
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="servicios.modelpaciente",
            ),
        ),
    ]
