# Generated by Django 4.1 on 2022-10-12 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0008_alter_modelservicio_paciente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelservicio",
            name="estudio",
            field=models.ManyToManyField(default=[], to="servicios.modelestudio"),
        ),
        migrations.AlterField(
            model_name="modelservicio",
            name="paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="servicios.modelpaciente",
            ),
        ),
    ]
