# Generated by Django 4.1 on 2022-10-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0010_alter_modelservicio_estudio"),
    ]

    operations = [
        migrations.RemoveField(model_name="modelservicio", name="estudio",),
    ]
