# Generated by Django 4.1 on 2022-10-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0011_remove_modelservicio_estudio"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelservicio",
            name="estudio",
            field=models.ManyToManyField(to="servicios.modelestudio"),
        ),
    ]
