# Generated by Django 4.1 on 2022-09-07 22:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Profile", new_name="Perfil",),
    ]
