# Generated by Django 4.1 on 2022-09-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiProfile", "0002_useraddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="points",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
